//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coqueta.Portal.Web.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoPorlIncidencia
    {
        public int Id { get; set; }
        public Nullable<int> lIncidenciasId { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Incidencia lIncidencia { get; set; }
    }
}
