//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coqueta.Incidencias.Web.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotesMontado
    {
        public string Lote { get; set; }
        public int Estilo { get; set; }
        public string Combinacion { get; set; }
        public string Suela { get; set; }
        public Nullable<int> NumSemana { get; set; }
        public Nullable<short> banda { get; set; }
        public short Pares { get; set; }
    }
}
