//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coqueta.Portal.Web.Datos.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        public short numeroLote { get; set; }
        public int pedido { get; set; }
        public System.DateTime fechaAdornoTerminado { get; set; }
        public Nullable<short> semanaEntrega { get; set; }
        public string caja { get; set; }
        public Nullable<System.DateTime> fechaCapturaLote { get; set; }
        public string colorEntreSuela { get; set; }
        public string colorForro { get; set; }
        public string colorPlantilla { get; set; }
        public string colorSuela { get; set; }
        public string color1 { get; set; }
        public string color2 { get; set; }
        public string color3 { get; set; }
        public string color4 { get; set; }
        public string color5 { get; set; }
        public string color6 { get; set; }
        public short paresCorrida1 { get; set; }
        public short paresCorrida2 { get; set; }
        public short paresCorrida3 { get; set; }
        public short paresCorrida4 { get; set; }
        public short paresCorrida5 { get; set; }
        public System.DateTime fechaAvanceCorte { get; set; }
        public Nullable<System.DateTime> fechaAvanceMontado { get; set; }
        public string claveLinea { get; set; }
        public Nullable<System.DateTime> fechaEntregaPlaneacion { get; set; }
        public int claveEstilo { get; set; }
        public Nullable<System.DateTime> fechaEntregaDestinatario { get; set; }
        public Nullable<System.DateTime> fechaCancelacionLote { get; set; }
        public string claveForro { get; set; }
        public string claveHorma { get; set; }
        public System.DateTime fechaInicioLote { get; set; }
        public string combinacion { get; set; }
        public short linea { get; set; }
        public Nullable<short> loteMaquila { get; set; }
        public string claveMarca { get; set; }
        public decimal costoMaterial1 { get; set; }
        public decimal costoMaterial2 { get; set; }
        public decimal costoMaterial3 { get; set; }
        public decimal costoMaterial4 { get; set; }
        public decimal costoMaterial5 { get; set; }
        public System.DateTime fechaMontado { get; set; }
        public short talla110Bebe { get; set; }
        public short talla115Bebe { get; set; }
        public short talla120Bebe { get; set; }
        public short talla100 { get; set; }
        public short talla105 { get; set; }
        public short talla110 { get; set; }
        public short talla115 { get; set; }
        public short talla120 { get; set; }
        public short talla125 { get; set; }
        public short talla130 { get; set; }
        public short talla135 { get; set; }
        public short talla140 { get; set; }
        public short talla145 { get; set; }
        public short talla150 { get; set; }
        public short talla155 { get; set; }
        public short talla160 { get; set; }
        public short talla165 { get; set; }
        public short talla170 { get; set; }
        public short talla175 { get; set; }
        public short talla180 { get; set; }
        public short talla185 { get; set; }
        public short talla190 { get; set; }
        public short talla195 { get; set; }
        public short talla200 { get; set; }
        public short talla205 { get; set; }
        public short talla210 { get; set; }
        public short talla215 { get; set; }
        public short talla220 { get; set; }
        public short talla225 { get; set; }
        public short talla230 { get; set; }
        public short talla235 { get; set; }
        public short talla240 { get; set; }
        public short talla245 { get; set; }
        public short talla250 { get; set; }
        public short talla255 { get; set; }
        public short talla260 { get; set; }
        public Nullable<short> talla265 { get; set; }
        public Nullable<short> talla270 { get; set; }
        public short talla900 { get; set; }
        public short talla905 { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fechaPespunte { get; set; }
        public System.DateTime fechaPespunteTerminado { get; set; }
        public string clavePiel1 { get; set; }
        public string clavePiel2 { get; set; }
        public string clavePiel3 { get; set; }
        public string clavePiel4 { get; set; }
        public string clavePiel5 { get; set; }
        public string clavePiel6 { get; set; }
        public System.DateTime fechaPreliminar { get; set; }
        public Nullable<short> proveedorMaquila { get; set; }
        public Nullable<int> referenciaLote { get; set; }
        public Nullable<int> semanaProgramadaEntregaLote { get; set; }
        public Nullable<int> semanaEntregaLote { get; set; }
        public Nullable<short> claveEstatusLote { get; set; }
        public short claveSubLinea { get; set; }
        public string claveSuela { get; set; }
        public System.DateTime fechaTerminadoFabricacion { get; set; }
        public Nullable<short> claveTipoNumeracion { get; set; }
        public string claveTipoPlantilla { get; set; }
        public short totalPares { get; set; }
        public Nullable<short> ultimoProceso { get; set; }
    }
}
